swagger: '2.0'
info:
  title: Private Pension
  version: '1.0'
  description: Esta documentação da API descreve os pontos finais e estruturas de dados 
    para uma aplicação de previdência privada. A API permite que os usuários gerenciem 
    produtos, clientes, contribuições para planos, resgates de planos e os próprios planos.
paths:
  /products:
    post:
      summary: Create a product
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Product data
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        '200':
          description: Product created successfully
          schema:
            $ref: '#/definitions/Product'
  /customers:
    post:
      summary: Create a customer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Customer data
          required: true
          schema:
            $ref: '#/definitions/Customer'
      responses:
        '200':
          description: Customer created successfully
          schema:
            $ref: '#/definitions/Customer'
  /plans/contribution:
    post:
      summary: Contribute to a plan
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Contribution data
          required: true
          schema:
            $ref: '#/definitions/Contribution'
      responses:
        '200':
          description: Contribution successful
          schema:
            $ref: '#/definitions/Contribution'
  /plans/redeem:
    post:
      summary: Redeem from a plan
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Redemption data
          required: true
          schema:
            $ref: '#/definitions/Redemption'
      responses:
        '200':
          description: Redemption successful
          schema:
            $ref: '#/definitions/Redemption'
  /plans:
    post:
      summary: Create a plan
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Plan data
          required: true
          schema:
            $ref: '#/definitions/Plan'
      responses:
        '200':
          description: Plan created successfully
          schema:
            $ref: '#/definitions/Plan'
definitions:
  Product:
    type: object
    properties:
      nome:
        type: string
      susep:
        type: string
      expiracaoDeVenda:
        type: string
        format: date-time
      valorMinimoAporteInicial:
        type: number
      valorMinimoAporteExtra:
        type: number
      idadeDeEntrada:
        type: integer
      idadeDeSaida:
        type: integer
      carenciaInicialDeResgate:
        type: integer
      carenciaEntreResgates:
        type: integer
  Customer:
    type: object
    properties:
      cpf:
        type: string
      nome:
        type: string
      email:
        type: string
        format: email
      dataDeNascimento:
        type: string
        format: date-time
      genero:
        type: string
      rendaMensal:
        type: number
  Contribution:
    type: object
    properties:
      idCliente:
        type: string
      idPlano:
        type: string
      valorAporte:
        type: number
  Redemption:
    type: object
    properties:
      idCliente:
        type: string
      idPlano:
        type: string
      valorResgate:
        type: number
  Plan:
    type: object
    properties:
      idCliente:
        type: string
      idProduto:
        type: string
      aporte:
        type: number
      dataDaContratacao:
        type: string
        format: date-time
      idadeDeAposentadoria:
        type: integer
